# Generated by Django 5.1.3 on 2024-12-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Folmamarket.uz%2Fuz&psig=AOvVaw1UjUk3nDasxRTmkn4Ql8J4&ust=1734696416461000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCMDP_fDls4oDFQAAAAAdAAAAABAE', upload_to='products/photos'),
        ),
    ]
